version: '3.8'

services:
  mongo1:
    image: mongo:5
    command: mongod --replSet lanaReplicaSet --bind_ip localhost,mongo1
    container_name: mongo1
    volumes:
      - mongo1-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - lanaNetwork

  mongo2:
    image: mongo:5
    command: mongod --replSet lanaReplicaSet --bind_ip localhost,mongo2
    container_name: mongo2
    volumes:
      - mongo2-data:/data/db
    ports:
      - "27018:27017"
    networks:
      - lanaNetwork

  mongo3:
    image: mongo:5
    command: mongod --replSet lanaReplicaSet --bind_ip localhost,mongo3
    container_name: mongo3
    volumes:
      - mongo3-data:/data/db
    ports:
      - "27019:27017"
    networks:
      - lanaNetwork

  lana_yolo5:
    image: mohamedabubaker09/lana_yolo5:ultralytics-yolov5-latest-cpu
    container_name: yolo5
    environment:
      - BUCKET_NAME=${BUCKET_NAME}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
    ports:
      - "8081:8081"
    networks:
      - lanaNetwork

  lana_bot:
    image: mohamedabubaker09/lana_bot:ubuntu-jammy-20231004-gpt
    container_name: lana_bot
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_APP_URL=${TELEGRAM_APP_URL}
      - BUCKET_NAME=${BUCKET_NAME}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - REGION=${REGION}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8443:8443"
    networks:
      - lanaNetwork

  mongo-init:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mongo-init
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  lanaNetwork:
    driver: bridge

volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data:

